services:
  - type: web
    name: campusquest-backend
    env: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://demo0752:Kishore0752@cluster0.cktbhpy.mongodb.net/gamification?retryWrites=true&w=majority
      - key: PORT
        value: 5000
